"""add_performance_indexes

Revision ID: 00e52db06a33
Revises: ca81cf371b8d
Create Date: 2026-04-05 15:19:03.995974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00e52db06a33'
down_revision: Union[str, Sequence[str], None] = 'ca81cf371b8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_attendance_institution_id'), 'attendance', ['institution_id'], unique=False)
    op.create_index(op.f('ix_attendance_student_id'), 'attendance', ['student_id'], unique=False)
    op.create_index(op.f('ix_marks_institution_id'), 'marks', ['institution_id'], unique=False)
    op.create_index(op.f('ix_marks_student_id'), 'marks', ['student_id'], unique=False)
    op.create_index(op.f('ix_students_institution_id'), 'students', ['institution_id'], unique=False)
    op.create_index(op.f('ix_teacher_assignments_institution_id'), 'teacher_assignments', ['institution_id'], unique=False)
    op.create_index(op.f('ix_teacher_assignments_teacher_id'), 'teacher_assignments', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_teachers_institution_id'), 'teachers', ['institution_id'], unique=False)
    op.create_index(op.f('ix_users_institution_id'), 'users', ['institution_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_institution_id'), table_name='users')
    op.drop_index(op.f('ix_teachers_institution_id'), table_name='teachers')
    op.drop_index(op.f('ix_teacher_assignments_teacher_id'), table_name='teacher_assignments')
    op.drop_index(op.f('ix_teacher_assignments_institution_id'), table_name='teacher_assignments')
    op.drop_index(op.f('ix_students_institution_id'), table_name='students')
    op.drop_index(op.f('ix_marks_student_id'), table_name='marks')
    op.drop_index(op.f('ix_marks_institution_id'), table_name='marks')
    op.drop_index(op.f('ix_attendance_student_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_institution_id'), table_name='attendance')
    # ### end Alembic commands ###
