"""extend_fee_structure_with_late_fees

Revision ID: 40725f2c5fc5
Revises: 18fc8cb8e614
Create Date: 2026-04-22 00:18:37.093093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40725f2c5fc5'
down_revision: Union[str, Sequence[str], None] = '18fc8cb8e614'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fee_structure', sa.Column('due_date', sa.Date(), nullable=True))
    op.add_column('fee_structure', sa.Column('late_fee_per_day', sa.Float(), nullable=True))
    op.add_column('fee_structure', sa.Column('max_late_fee', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fee_structure', 'max_late_fee')
    op.drop_column('fee_structure', 'late_fee_per_day')
    op.drop_column('fee_structure', 'due_date')
    # ### end Alembic commands ###
