"""Update Announcement model

Revision ID: 4dce1a41051f
Revises: 2f05160b3b56
Create Date: 2026-04-05 19:15:47.875601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dce1a41051f'
down_revision: Union[str, Sequence[str], None] = '2f05160b3b56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('audience', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_announcements_created_by_id', 'users', ['created_by_id'], ['id'])
        batch_op.drop_column('target_role')
        batch_op.drop_column('content')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('target_role', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint('fk_announcements_created_by_id', type_='foreignkey')
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('expires_at')
        batch_op.drop_column('audience')
        batch_op.drop_column('message')

    # ### end Alembic commands ###
