"""add_student_fee_unique_constraint

Revision ID: 532c991aa9b9
Revises: bb8c9795bca0
Create Date: 2026-04-24 18:31:13.082012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '532c991aa9b9'
down_revision: Union[str, Sequence[str], None] = 'bb8c9795bca0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_student_fees_student_class', 'student_fees', ['student_id', 'class_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_student_fees_student_class', table_name='student_fees')
    # ### end Alembic commands ###
    # ### end Alembic commands ###
