"""add_cron_lock_table

Revision ID: 5aedf1519642
Revises: 532c991aa9b9
Create Date: 2026-04-24 18:33:41.367206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5aedf1519642'
down_revision: Union[str, Sequence[str], None] = '532c991aa9b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cron_locks',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cron_locks')
    # ### end Alembic commands ###
    # ### end Alembic commands ###
