"""add_student_fee_table

Revision ID: 6269164509a4
Revises: b5ac571fe81a
Create Date: 2026-04-24 18:05:02.129950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6269164509a4'
down_revision: Union[str, Sequence[str], None] = 'b5ac571fe81a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_fees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('amount_paid', sa.Float(), nullable=True),
    sa.Column('due_amount', sa.Float(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('UNPAID', 'PARTIAL', 'PAID', name='studentfeestatus'), nullable=True),
    sa.Column('last_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_called_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['school_classes.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_fees_class_id'), 'student_fees', ['class_id'], unique=False)
    op.create_index(op.f('ix_student_fees_id'), 'student_fees', ['id'], unique=False)
    op.create_index(op.f('ix_student_fees_institution_id'), 'student_fees', ['institution_id'], unique=False)
    op.create_index(op.f('ix_student_fees_status'), 'student_fees', ['status'], unique=False)
    op.create_index(op.f('ix_student_fees_student_id'), 'student_fees', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_fees_student_id'), table_name='student_fees')
    op.drop_index(op.f('ix_student_fees_status'), table_name='student_fees')
    op.drop_index(op.f('ix_student_fees_institution_id'), table_name='student_fees')
    op.drop_index(op.f('ix_student_fees_id'), table_name='student_fees')
    op.drop_index(op.f('ix_student_fees_class_id'), table_name='student_fees')
    op.drop_table('student_fees')
    # Use bind().execute to drop the enum if necessary, or let Alembic handle it if it was created with sa.Enum
    # op.execute("DROP TYPE studentfeestatus")
    # ### end Alembic commands ###
    # ### end Alembic commands ###
