"""clean baseline

Revision ID: a6d38a450102
Revises: 
Create Date: 2026-05-31 15:13:45.673879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6d38a450102'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cron_locks',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('institutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institutions_deleted_at'), 'institutions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_institutions_id'), 'institutions', ['id'], unique=False)
    op.create_index(op.f('ix_institutions_name'), 'institutions', ['name'], unique=False)
    op.create_index(op.f('ix_institutions_slug'), 'institutions', ['slug'], unique=True)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('end_date', sa.String(), nullable=True),
    sa.Column('time', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('is_holiday', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('visibility', sa.JSON(), nullable=True),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix_events_institution_id'), 'events', ['institution_id'], unique=False)
    op.create_index(op.f('ix_events_title'), 'events', ['title'], unique=False)
    op.create_table('grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('tuition_fee', sa.Float(), nullable=True),
    sa.Column('fee_due_date', sa.Date(), nullable=True),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grades_id'), 'grades', ['id'], unique=False)
    op.create_index(op.f('ix_grades_institution_id'), 'grades', ['institution_id'], unique=False)
    op.create_table('schedule_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('period_type', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_periods_id'), 'schedule_periods', ['id'], unique=False)
    op.create_index(op.f('ix_schedule_periods_institution_id'), 'schedule_periods', ['institution_id'], unique=False)
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subjects_code'), 'subjects', ['code'], unique=False)
    op.create_index(op.f('ix_subjects_id'), 'subjects', ['id'], unique=False)
    op.create_index(op.f('ix_subjects_institution_id'), 'subjects', ['institution_id'], unique=False)
    op.create_index(op.f('ix_subjects_name'), 'subjects', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=True),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_institution_id'), 'audit_logs', ['institution_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('device_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('expo_push_token', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('device_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('invalidated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_tokens_expo_push_token'), 'device_tokens', ['expo_push_token'], unique=True)
    op.create_index(op.f('ix_device_tokens_id'), 'device_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_device_tokens_institution_id'), 'device_tokens', ['institution_id'], unique=False)
    op.create_index(op.f('ix_device_tokens_is_active'), 'device_tokens', ['is_active'], unique=False)
    op.create_index('ix_device_tokens_user_active', 'device_tokens', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_device_tokens_user_id'), 'device_tokens', ['user_id'], unique=False)
    op.create_table('fee_reminder_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('automation_mode', sa.String(length=20), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('day_of_month', sa.Integer(), nullable=True),
    sa.Column('send_hour', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('overdue_days', sa.Integer(), nullable=True),
    sa.Column('cooldown_days', sa.Integer(), nullable=True),
    sa.Column('voice_calls_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_summary', sa.Text(), nullable=True),
    sa.Column('last_run_triggered_by', sa.String(length=40), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_reminder_settings_id'), 'fee_reminder_settings', ['id'], unique=False)
    op.create_index(op.f('ix_fee_reminder_settings_institution_id'), 'fee_reminder_settings', ['institution_id'], unique=True)
    op.create_table('institution_payment_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('upi_id', sa.String(length=160), nullable=True),
    sa.Column('upi_display_name', sa.String(length=200), nullable=True),
    sa.Column('bank_name', sa.String(length=200), nullable=True),
    sa.Column('bank_account_number', sa.String(length=80), nullable=True),
    sa.Column('bank_ifsc', sa.String(length=40), nullable=True),
    sa.Column('bank_account_holder', sa.String(length=200), nullable=True),
    sa.Column('qr_image_url', sa.String(length=1024), nullable=True),
    sa.Column('payment_instructions', sa.Text(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institution_payment_settings_id'), 'institution_payment_settings', ['id'], unique=False)
    op.create_index(op.f('ix_institution_payment_settings_institution_id'), 'institution_payment_settings', ['institution_id'], unique=True)
    op.create_table('parents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('primary_phone', sa.String(), nullable=True),
    sa.Column('secondary_phone', sa.String(), nullable=True),
    sa.Column('primary_phone_normalized', sa.String(length=10), nullable=True),
    sa.Column('relation', sa.String(), nullable=True),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_parents_email'), 'parents', ['email'], unique=False)
    op.create_index(op.f('ix_parents_id'), 'parents', ['id'], unique=False)
    op.create_index(op.f('ix_parents_institution_id'), 'parents', ['institution_id'], unique=False)
    op.create_index(op.f('ix_parents_name'), 'parents', ['name'], unique=False)
    op.create_index(op.f('ix_parents_primary_phone_normalized'), 'parents', ['primary_phone_normalized'], unique=False)
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('grade_id', sa.Integer(), nullable=True),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sections_grade_id'), 'sections', ['grade_id'], unique=False)
    op.create_index(op.f('ix_sections_id'), 'sections', ['id'], unique=False)
    op.create_index(op.f('ix_sections_institution_id'), 'sections', ['institution_id'], unique=False)
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('whatsapp', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('plain_password', sa.String(), nullable=True),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_teachers_id'), 'teachers', ['id'], unique=False)
    op.create_index(op.f('ix_teachers_institution_id'), 'teachers', ['institution_id'], unique=False)
    op.create_index(op.f('ix_teachers_name'), 'teachers', ['name'], unique=False)
    op.create_table('push_delivery_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.String(), nullable=False),
    sa.Column('reference_id', sa.String(), nullable=True),
    sa.Column('device_token_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('expo_ticket_id', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_token_id'], ['device_tokens.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_push_delivery_logs_id'), 'push_delivery_logs', ['id'], unique=False)
    op.create_index(op.f('ix_push_delivery_logs_institution_id'), 'push_delivery_logs', ['institution_id'], unique=False)
    op.create_index(op.f('ix_push_delivery_logs_notification_type'), 'push_delivery_logs', ['notification_type'], unique=False)
    op.create_index(op.f('ix_push_delivery_logs_reference_id'), 'push_delivery_logs', ['reference_id'], unique=False)
    op.create_index(op.f('ix_push_delivery_logs_status'), 'push_delivery_logs', ['status'], unique=False)
    op.create_index(op.f('ix_push_delivery_logs_user_id'), 'push_delivery_logs', ['user_id'], unique=False)
    op.create_table('school_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grade_id', sa.Integer(), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('room_number', sa.String(), nullable=True),
    sa.Column('tuition_fee', sa.Float(), nullable=False),
    sa.Column('transport_fee', sa.Float(), nullable=True),
    sa.Column('other_fee', sa.Float(), nullable=True),
    sa.Column('total_fee', sa.Float(), nullable=True),
    sa.Column('fee_due_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_school_classes_id'), 'school_classes', ['id'], unique=False)
    op.create_table('teacher_attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('check_in_time', sa.String(), nullable=True),
    sa.Column('check_out_time', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('is_edited', sa.Integer(), nullable=True),
    sa.Column('edited_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['edited_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_attendance_date'), 'teacher_attendance', ['date'], unique=False)
    op.create_index(op.f('ix_teacher_attendance_id'), 'teacher_attendance', ['id'], unique=False)
    op.create_index('ix_teacher_attendance_inst_date', 'teacher_attendance', ['institution_id', 'date'], unique=False)
    op.create_index(op.f('ix_teacher_attendance_institution_id'), 'teacher_attendance', ['institution_id'], unique=False)
    op.create_index('ix_teacher_attendance_teacher_date', 'teacher_attendance', ['teacher_id', 'date'], unique=True)
    op.create_index(op.f('ix_teacher_attendance_teacher_id'), 'teacher_attendance', ['teacher_id'], unique=False)
    op.create_table('teacher_leave_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('leave_type', sa.String(), nullable=False),
    sa.Column('start_date', sa.String(), nullable=False),
    sa.Column('end_date', sa.String(), nullable=False),
    sa.Column('days_count', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_teacher_leave_inst_status', 'teacher_leave_requests', ['institution_id', 'status'], unique=False)
    op.create_index('ix_teacher_leave_inst_teacher', 'teacher_leave_requests', ['institution_id', 'teacher_id'], unique=False)
    op.create_index(op.f('ix_teacher_leave_requests_id'), 'teacher_leave_requests', ['id'], unique=False)
    op.create_index(op.f('ix_teacher_leave_requests_institution_id'), 'teacher_leave_requests', ['institution_id'], unique=False)
    op.create_index(op.f('ix_teacher_leave_requests_teacher_id'), 'teacher_leave_requests', ['teacher_id'], unique=False)
    op.create_table('uploaded_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('storage_backend', sa.String(length=16), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('extraction_status', sa.String(length=16), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('subject', sa.String(length=120), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('file_type', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source_school_id', sa.String(length=64), nullable=True),
    sa.Column('source_teacher_id', sa.String(length=64), nullable=True),
    sa.Column('source_grade_id', sa.String(length=64), nullable=True),
    sa.Column('source_subject_id', sa.String(length=64), nullable=True),
    sa.Column('source_chapter_id', sa.String(length=64), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploaded_files_file_type'), 'uploaded_files', ['file_type'], unique=False)
    op.create_index(op.f('ix_uploaded_files_id'), 'uploaded_files', ['id'], unique=False)
    op.create_index(op.f('ix_uploaded_files_institution_id'), 'uploaded_files', ['institution_id'], unique=False)
    op.create_index(op.f('ix_uploaded_files_is_deleted'), 'uploaded_files', ['is_deleted'], unique=False)
    op.create_index('ix_uploaded_files_owner_active', 'uploaded_files', ['teacher_id', 'is_deleted'], unique=False)
    op.create_index('ix_uploaded_files_owner_type', 'uploaded_files', ['teacher_id', 'file_type'], unique=False)
    op.create_index(op.f('ix_uploaded_files_teacher_id'), 'uploaded_files', ['teacher_id'], unique=False)
    op.create_index('ix_uploaded_files_uploaded_at', 'uploaded_files', ['uploaded_at'], unique=False)
    op.create_table('exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('term', sa.String(), nullable=True),
    sa.Column('school_class_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['school_class_id'], ['school_classes.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exams_id'), 'exams', ['id'], unique=False)
    op.create_index(op.f('ix_exams_institution_id'), 'exams', ['institution_id'], unique=False)
    op.create_index(op.f('ix_exams_name'), 'exams', ['name'], unique=False)
    op.create_index(op.f('ix_exams_school_class_id'), 'exams', ['school_class_id'], unique=False)
    op.create_index(op.f('ix_exams_subject_id'), 'exams', ['subject_id'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('dob', sa.String(), nullable=True),
    sa.Column('whatsapp', sa.String(), nullable=True),
    sa.Column('school_class_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('plain_password', sa.String(), nullable=True),
    sa.Column('roll_number', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('blood_group', sa.String(), nullable=True),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ),
    sa.ForeignKeyConstraint(['school_class_id'], ['school_classes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    op.create_index(op.f('ix_students_institution_id'), 'students', ['institution_id'], unique=False)
    op.create_index(op.f('ix_students_name'), 'students', ['name'], unique=False)
    op.create_index(op.f('ix_students_parent_id'), 'students', ['parent_id'], unique=False)
    op.create_index(op.f('ix_students_roll_number'), 'students', ['roll_number'], unique=False)
    op.create_index(op.f('ix_students_school_class_id'), 'students', ['school_class_id'], unique=False)
    op.create_table('teacher_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('school_class_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['school_class_id'], ['school_classes.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_assignments_id'), 'teacher_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_teacher_assignments_institution_id'), 'teacher_assignments', ['institution_id'], unique=False)
    op.create_index(op.f('ix_teacher_assignments_school_class_id'), 'teacher_assignments', ['school_class_id'], unique=False)
    op.create_index(op.f('ix_teacher_assignments_subject_id'), 'teacher_assignments', ['subject_id'], unique=False)
    op.create_index(op.f('ix_teacher_assignments_teacher_id'), 'teacher_assignments', ['teacher_id'], unique=False)
    op.create_table('teacher_attendance_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('attendance_id', sa.Integer(), nullable=True),
    sa.Column('changed_by_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['attendance_id'], ['teacher_attendance.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_attendance_audit_logs_id'), 'teacher_attendance_audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_teacher_attendance_audit_logs_institution_id'), 'teacher_attendance_audit_logs', ['institution_id'], unique=False)
    op.create_index(op.f('ix_teacher_attendance_audit_logs_teacher_id'), 'teacher_attendance_audit_logs', ['teacher_id'], unique=False)
    op.create_index('ix_teacher_audit_inst_teacher', 'teacher_attendance_audit_logs', ['institution_id', 'teacher_id'], unique=False)
    op.create_table('timetable_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('school_class_id', sa.Integer(), nullable=False),
    sa.Column('schedule_period_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('room', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['schedule_period_id'], ['schedule_periods.id'], ),
    sa.ForeignKeyConstraint(['school_class_id'], ['school_classes.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_class_id', 'schedule_period_id', 'day_of_week', name='uq_timetable_class_period_day')
    )
    op.create_index(op.f('ix_timetable_slots_id'), 'timetable_slots', ['id'], unique=False)
    op.create_index(op.f('ix_timetable_slots_institution_id'), 'timetable_slots', ['institution_id'], unique=False)
    op.create_index(op.f('ix_timetable_slots_schedule_period_id'), 'timetable_slots', ['schedule_period_id'], unique=False)
    op.create_index(op.f('ix_timetable_slots_school_class_id'), 'timetable_slots', ['school_class_id'], unique=False)
    op.create_table('announcements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('CLASS', 'STUDENT', name='announcementtype', native_enum=False), nullable=False),
    sa.Column('priority', sa.Enum('NORMAL', 'IMPORTANT', name='announcementpriority', native_enum=False), nullable=False),
    sa.Column('category', sa.Enum('NORMAL', 'HOMEWORK', name='announcementcategory', native_enum=False), server_default='NORMAL', nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subject', sa.String(length=120), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('attachment_url', sa.String(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['school_classes.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_announcements_category', 'announcements', ['category'], unique=False)
    op.create_index('ix_announcements_class_id', 'announcements', ['class_id'], unique=False)
    op.create_index('ix_announcements_created_at_desc', 'announcements', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_announcements_student_id', 'announcements', ['student_id'], unique=False)
    op.create_index('ix_announcements_teacher_id', 'announcements', ['teacher_id'], unique=False)
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('school_class_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['school_class_id'], ['school_classes.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attendance_class_date_institution', 'attendance', ['school_class_id', 'date', 'institution_id'], unique=False)
    op.create_index(op.f('ix_attendance_date'), 'attendance', ['date'], unique=False)
    op.create_index(op.f('ix_attendance_id'), 'attendance', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_institution_id'), 'attendance', ['institution_id'], unique=False)
    op.create_index(op.f('ix_attendance_school_class_id'), 'attendance', ['school_class_id'], unique=False)
    op.create_index(op.f('ix_attendance_student_id'), 'attendance', ['student_id'], unique=False)
    op.create_index('ix_attendance_student_institution_subject_date', 'attendance', ['student_id', 'institution_id', 'subject', 'date'], unique=False)
    op.create_index(op.f('ix_attendance_subject_id'), 'attendance', ['subject_id'], unique=False)
    op.create_table('manual_payment_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('submitted_by_user_id', sa.Integer(), nullable=False),
    sa.Column('student_name', sa.String(length=200), nullable=False),
    sa.Column('parent_name', sa.String(length=200), nullable=False),
    sa.Column('class_name', sa.String(length=120), nullable=True),
    sa.Column('section_name', sa.String(length=40), nullable=True),
    sa.Column('fee_type', sa.String(length=40), nullable=True),
    sa.Column('installment_label', sa.String(length=120), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('approved_amount', sa.Float(), nullable=True),
    sa.Column('transaction_reference', sa.String(length=120), nullable=False),
    sa.Column('transaction_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payer_name', sa.String(length=200), nullable=True),
    sa.Column('payer_upi', sa.String(length=120), nullable=True),
    sa.Column('screenshot_url', sa.String(length=1024), nullable=True),
    sa.Column('parent_note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('receipt_number', sa.String(length=80), nullable=True),
    sa.Column('receipt_url', sa.String(length=1024), nullable=True),
    sa.Column('receipt_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_manual_payment_requests_dedupe', 'manual_payment_requests', ['institution_id', 'student_id', 'transaction_reference'], unique=False)
    op.create_index(op.f('ix_manual_payment_requests_id'), 'manual_payment_requests', ['id'], unique=False)
    op.create_index('ix_manual_payment_requests_inst_status', 'manual_payment_requests', ['institution_id', 'status'], unique=False)
    op.create_index('ix_manual_payment_requests_inst_submitted_at', 'manual_payment_requests', ['institution_id', 'submitted_at'], unique=False)
    op.create_index(op.f('ix_manual_payment_requests_institution_id'), 'manual_payment_requests', ['institution_id'], unique=False)
    op.create_index(op.f('ix_manual_payment_requests_receipt_number'), 'manual_payment_requests', ['receipt_number'], unique=True)
    op.create_index(op.f('ix_manual_payment_requests_status'), 'manual_payment_requests', ['status'], unique=False)
    op.create_index(op.f('ix_manual_payment_requests_student_id'), 'manual_payment_requests', ['student_id'], unique=False)
    op.create_index(op.f('ix_manual_payment_requests_submitted_at'), 'manual_payment_requests', ['submitted_at'], unique=False)
    op.create_index(op.f('ix_manual_payment_requests_transaction_reference'), 'manual_payment_requests', ['transaction_reference'], unique=False)
    op.create_table('marks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('exam_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('test_name', sa.String(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('max_score', sa.Integer(), nullable=True),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marks_exam_id'), 'marks', ['exam_id'], unique=False)
    op.create_index('ix_marks_exam_institution_student', 'marks', ['exam_id', 'institution_id', 'student_id'], unique=False)
    op.create_index(op.f('ix_marks_id'), 'marks', ['id'], unique=False)
    op.create_index(op.f('ix_marks_institution_id'), 'marks', ['institution_id'], unique=False)
    op.create_index(op.f('ix_marks_student_id'), 'marks', ['student_id'], unique=False)
    op.create_index('ix_marks_student_institution_test_subject', 'marks', ['student_id', 'institution_id', 'test_name', 'subject'], unique=False)
    op.create_index(op.f('ix_marks_subject_id'), 'marks', ['subject_id'], unique=False)
    op.create_index(op.f('ix_marks_teacher_id'), 'marks', ['teacher_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('payment_mode', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_institution_id'), 'payments', ['institution_id'], unique=False)
    op.create_index(op.f('ix_payments_student_id'), 'payments', ['student_id'], unique=False)
    op.create_table('student_fees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('amount_paid', sa.Float(), nullable=True),
    sa.Column('due_amount', sa.Float(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('UNPAID', 'PARTIAL', 'PAID', name='studentfeestatus', native_enum=False), nullable=True),
    sa.Column('last_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_called_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['school_classes.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_fees_class_id'), 'student_fees', ['class_id'], unique=False)
    op.create_index(op.f('ix_student_fees_id'), 'student_fees', ['id'], unique=False)
    op.create_index(op.f('ix_student_fees_institution_id'), 'student_fees', ['institution_id'], unique=False)
    op.create_index(op.f('ix_student_fees_last_called_at'), 'student_fees', ['last_called_at'], unique=False)
    op.create_index(op.f('ix_student_fees_last_notified_at'), 'student_fees', ['last_notified_at'], unique=False)
    op.create_index(op.f('ix_student_fees_status'), 'student_fees', ['status'], unique=False)
    op.create_index('ix_student_fees_student_class', 'student_fees', ['student_id', 'class_id'], unique=True)
    op.create_index(op.f('ix_student_fees_student_id'), 'student_fees', ['student_id'], unique=False)
    op.create_table('announcement_reads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('announcement_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('announcement_id', 'parent_id', name='uq_announcement_parent_read')
    )
    op.create_table('finance_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_number', sa.String(), nullable=False),
    sa.Column('entry_type', sa.Enum('PAYMENT', 'REFUND', 'ADJUSTMENT', name='ledgerentrytype', native_enum=False), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('manual_payment_request_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('student_name', sa.String(), nullable=False),
    sa.Column('class_name', sa.String(), nullable=True),
    sa.Column('fee_type', sa.String(), nullable=True),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('external_reference', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('gateway_fee', sa.Float(), nullable=True),
    sa.Column('net_amount', sa.Float(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=False),
    sa.Column('payment_status', sa.String(), nullable=False),
    sa.Column('payment_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('recorded_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['school_classes.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['manual_payment_request_id'], ['manual_payment_requests.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_ledger_academic_year'), 'finance_ledger', ['academic_year'], unique=False)
    op.create_index(op.f('ix_finance_ledger_class_id'), 'finance_ledger', ['class_id'], unique=False)
    op.create_index(op.f('ix_finance_ledger_entry_type'), 'finance_ledger', ['entry_type'], unique=False)
    op.create_index(op.f('ix_finance_ledger_external_reference'), 'finance_ledger', ['external_reference'], unique=False)
    op.create_index(op.f('ix_finance_ledger_id'), 'finance_ledger', ['id'], unique=False)
    op.create_index(op.f('ix_finance_ledger_institution_id'), 'finance_ledger', ['institution_id'], unique=False)
    op.create_index(op.f('ix_finance_ledger_manual_payment_request_id'), 'finance_ledger', ['manual_payment_request_id'], unique=False)
    op.create_index(op.f('ix_finance_ledger_payment_date'), 'finance_ledger', ['payment_date'], unique=False)
    op.create_index('ix_finance_ledger_payment_date_inst', 'finance_ledger', ['institution_id', 'payment_date'], unique=False)
    op.create_index(op.f('ix_finance_ledger_payment_id'), 'finance_ledger', ['payment_id'], unique=False)
    op.create_index(op.f('ix_finance_ledger_payment_status'), 'finance_ledger', ['payment_status'], unique=False)
    op.create_index(op.f('ix_finance_ledger_receipt_number'), 'finance_ledger', ['receipt_number'], unique=True)
    op.create_index(op.f('ix_finance_ledger_student_id'), 'finance_ledger', ['student_id'], unique=False)
    op.create_index('ix_finance_ledger_student_inst', 'finance_ledger', ['institution_id', 'student_id'], unique=False)
    op.create_table('homework_confirmations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('announcement_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('announcement_id', 'student_id', name='uq_homework_confirmation_student')
    )
    op.create_index('ix_homework_confirmations_announcement', 'homework_confirmations', ['announcement_id'], unique=False)
    op.create_index('ix_homework_confirmations_student', 'homework_confirmations', ['student_id'], unique=False)
    op.create_table('manual_payment_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_request_id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=60), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('actor_role', sa.String(length=40), nullable=True),
    sa.Column('actor_name', sa.String(length=200), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('from_status', sa.String(length=40), nullable=True),
    sa.Column('to_status', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['payment_request_id'], ['manual_payment_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manual_payment_audit_logs_created_at'), 'manual_payment_audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_manual_payment_audit_logs_event'), 'manual_payment_audit_logs', ['event'], unique=False)
    op.create_index(op.f('ix_manual_payment_audit_logs_id'), 'manual_payment_audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_manual_payment_audit_logs_institution_id'), 'manual_payment_audit_logs', ['institution_id'], unique=False)
    op.create_index(op.f('ix_manual_payment_audit_logs_payment_request_id'), 'manual_payment_audit_logs', ['payment_request_id'], unique=False)
    op.create_table('payment_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('fee_type', sa.String(), nullable=True),
    sa.Column('allocated_amount', sa.Float(), nullable=True),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_allocations_id'), 'payment_allocations', ['id'], unique=False)
    op.create_index(op.f('ix_payment_allocations_institution_id'), 'payment_allocations', ['institution_id'], unique=False)
    op.create_index(op.f('ix_payment_allocations_payment_id'), 'payment_allocations', ['payment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_allocations_payment_id'), table_name='payment_allocations')
    op.drop_index(op.f('ix_payment_allocations_institution_id'), table_name='payment_allocations')
    op.drop_index(op.f('ix_payment_allocations_id'), table_name='payment_allocations')
    op.drop_table('payment_allocations')
    op.drop_index(op.f('ix_manual_payment_audit_logs_payment_request_id'), table_name='manual_payment_audit_logs')
    op.drop_index(op.f('ix_manual_payment_audit_logs_institution_id'), table_name='manual_payment_audit_logs')
    op.drop_index(op.f('ix_manual_payment_audit_logs_id'), table_name='manual_payment_audit_logs')
    op.drop_index(op.f('ix_manual_payment_audit_logs_event'), table_name='manual_payment_audit_logs')
    op.drop_index(op.f('ix_manual_payment_audit_logs_created_at'), table_name='manual_payment_audit_logs')
    op.drop_table('manual_payment_audit_logs')
    op.drop_index('ix_homework_confirmations_student', table_name='homework_confirmations')
    op.drop_index('ix_homework_confirmations_announcement', table_name='homework_confirmations')
    op.drop_table('homework_confirmations')
    op.drop_index('ix_finance_ledger_student_inst', table_name='finance_ledger')
    op.drop_index(op.f('ix_finance_ledger_student_id'), table_name='finance_ledger')
    op.drop_index(op.f('ix_finance_ledger_receipt_number'), table_name='finance_ledger')
    op.drop_index(op.f('ix_finance_ledger_payment_status'), table_name='finance_ledger')
    op.drop_index(op.f('ix_finance_ledger_payment_id'), table_name='finance_ledger')
    op.drop_index('ix_finance_ledger_payment_date_inst', table_name='finance_ledger')
    op.drop_index(op.f('ix_finance_ledger_payment_date'), table_name='finance_ledger')
    op.drop_index(op.f('ix_finance_ledger_manual_payment_request_id'), table_name='finance_ledger')
    op.drop_index(op.f('ix_finance_ledger_institution_id'), table_name='finance_ledger')
    op.drop_index(op.f('ix_finance_ledger_id'), table_name='finance_ledger')
    op.drop_index(op.f('ix_finance_ledger_external_reference'), table_name='finance_ledger')
    op.drop_index(op.f('ix_finance_ledger_entry_type'), table_name='finance_ledger')
    op.drop_index(op.f('ix_finance_ledger_class_id'), table_name='finance_ledger')
    op.drop_index(op.f('ix_finance_ledger_academic_year'), table_name='finance_ledger')
    op.drop_table('finance_ledger')
    op.drop_table('announcement_reads')
    op.drop_index(op.f('ix_student_fees_student_id'), table_name='student_fees')
    op.drop_index('ix_student_fees_student_class', table_name='student_fees')
    op.drop_index(op.f('ix_student_fees_status'), table_name='student_fees')
    op.drop_index(op.f('ix_student_fees_last_notified_at'), table_name='student_fees')
    op.drop_index(op.f('ix_student_fees_last_called_at'), table_name='student_fees')
    op.drop_index(op.f('ix_student_fees_institution_id'), table_name='student_fees')
    op.drop_index(op.f('ix_student_fees_id'), table_name='student_fees')
    op.drop_index(op.f('ix_student_fees_class_id'), table_name='student_fees')
    op.drop_table('student_fees')
    op.drop_index(op.f('ix_payments_student_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_institution_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_marks_teacher_id'), table_name='marks')
    op.drop_index(op.f('ix_marks_subject_id'), table_name='marks')
    op.drop_index('ix_marks_student_institution_test_subject', table_name='marks')
    op.drop_index(op.f('ix_marks_student_id'), table_name='marks')
    op.drop_index(op.f('ix_marks_institution_id'), table_name='marks')
    op.drop_index(op.f('ix_marks_id'), table_name='marks')
    op.drop_index('ix_marks_exam_institution_student', table_name='marks')
    op.drop_index(op.f('ix_marks_exam_id'), table_name='marks')
    op.drop_table('marks')
    op.drop_index(op.f('ix_manual_payment_requests_transaction_reference'), table_name='manual_payment_requests')
    op.drop_index(op.f('ix_manual_payment_requests_submitted_at'), table_name='manual_payment_requests')
    op.drop_index(op.f('ix_manual_payment_requests_student_id'), table_name='manual_payment_requests')
    op.drop_index(op.f('ix_manual_payment_requests_status'), table_name='manual_payment_requests')
    op.drop_index(op.f('ix_manual_payment_requests_receipt_number'), table_name='manual_payment_requests')
    op.drop_index(op.f('ix_manual_payment_requests_institution_id'), table_name='manual_payment_requests')
    op.drop_index('ix_manual_payment_requests_inst_submitted_at', table_name='manual_payment_requests')
    op.drop_index('ix_manual_payment_requests_inst_status', table_name='manual_payment_requests')
    op.drop_index(op.f('ix_manual_payment_requests_id'), table_name='manual_payment_requests')
    op.drop_index('ix_manual_payment_requests_dedupe', table_name='manual_payment_requests')
    op.drop_table('manual_payment_requests')
    op.drop_index(op.f('ix_attendance_subject_id'), table_name='attendance')
    op.drop_index('ix_attendance_student_institution_subject_date', table_name='attendance')
    op.drop_index(op.f('ix_attendance_student_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_school_class_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_institution_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_date'), table_name='attendance')
    op.drop_index('ix_attendance_class_date_institution', table_name='attendance')
    op.drop_table('attendance')
    op.drop_index('ix_announcements_teacher_id', table_name='announcements')
    op.drop_index('ix_announcements_student_id', table_name='announcements')
    op.drop_index('ix_announcements_created_at_desc', table_name='announcements')
    op.drop_index('ix_announcements_class_id', table_name='announcements')
    op.drop_index('ix_announcements_category', table_name='announcements')
    op.drop_table('announcements')
    op.drop_index(op.f('ix_timetable_slots_school_class_id'), table_name='timetable_slots')
    op.drop_index(op.f('ix_timetable_slots_schedule_period_id'), table_name='timetable_slots')
    op.drop_index(op.f('ix_timetable_slots_institution_id'), table_name='timetable_slots')
    op.drop_index(op.f('ix_timetable_slots_id'), table_name='timetable_slots')
    op.drop_table('timetable_slots')
    op.drop_index('ix_teacher_audit_inst_teacher', table_name='teacher_attendance_audit_logs')
    op.drop_index(op.f('ix_teacher_attendance_audit_logs_teacher_id'), table_name='teacher_attendance_audit_logs')
    op.drop_index(op.f('ix_teacher_attendance_audit_logs_institution_id'), table_name='teacher_attendance_audit_logs')
    op.drop_index(op.f('ix_teacher_attendance_audit_logs_id'), table_name='teacher_attendance_audit_logs')
    op.drop_table('teacher_attendance_audit_logs')
    op.drop_index(op.f('ix_teacher_assignments_teacher_id'), table_name='teacher_assignments')
    op.drop_index(op.f('ix_teacher_assignments_subject_id'), table_name='teacher_assignments')
    op.drop_index(op.f('ix_teacher_assignments_school_class_id'), table_name='teacher_assignments')
    op.drop_index(op.f('ix_teacher_assignments_institution_id'), table_name='teacher_assignments')
    op.drop_index(op.f('ix_teacher_assignments_id'), table_name='teacher_assignments')
    op.drop_table('teacher_assignments')
    op.drop_index(op.f('ix_students_school_class_id'), table_name='students')
    op.drop_index(op.f('ix_students_roll_number'), table_name='students')
    op.drop_index(op.f('ix_students_parent_id'), table_name='students')
    op.drop_index(op.f('ix_students_name'), table_name='students')
    op.drop_index(op.f('ix_students_institution_id'), table_name='students')
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_exams_subject_id'), table_name='exams')
    op.drop_index(op.f('ix_exams_school_class_id'), table_name='exams')
    op.drop_index(op.f('ix_exams_name'), table_name='exams')
    op.drop_index(op.f('ix_exams_institution_id'), table_name='exams')
    op.drop_index(op.f('ix_exams_id'), table_name='exams')
    op.drop_table('exams')
    op.drop_index('ix_uploaded_files_uploaded_at', table_name='uploaded_files')
    op.drop_index(op.f('ix_uploaded_files_teacher_id'), table_name='uploaded_files')
    op.drop_index('ix_uploaded_files_owner_type', table_name='uploaded_files')
    op.drop_index('ix_uploaded_files_owner_active', table_name='uploaded_files')
    op.drop_index(op.f('ix_uploaded_files_is_deleted'), table_name='uploaded_files')
    op.drop_index(op.f('ix_uploaded_files_institution_id'), table_name='uploaded_files')
    op.drop_index(op.f('ix_uploaded_files_id'), table_name='uploaded_files')
    op.drop_index(op.f('ix_uploaded_files_file_type'), table_name='uploaded_files')
    op.drop_table('uploaded_files')
    op.drop_index(op.f('ix_teacher_leave_requests_teacher_id'), table_name='teacher_leave_requests')
    op.drop_index(op.f('ix_teacher_leave_requests_institution_id'), table_name='teacher_leave_requests')
    op.drop_index(op.f('ix_teacher_leave_requests_id'), table_name='teacher_leave_requests')
    op.drop_index('ix_teacher_leave_inst_teacher', table_name='teacher_leave_requests')
    op.drop_index('ix_teacher_leave_inst_status', table_name='teacher_leave_requests')
    op.drop_table('teacher_leave_requests')
    op.drop_index(op.f('ix_teacher_attendance_teacher_id'), table_name='teacher_attendance')
    op.drop_index('ix_teacher_attendance_teacher_date', table_name='teacher_attendance')
    op.drop_index(op.f('ix_teacher_attendance_institution_id'), table_name='teacher_attendance')
    op.drop_index('ix_teacher_attendance_inst_date', table_name='teacher_attendance')
    op.drop_index(op.f('ix_teacher_attendance_id'), table_name='teacher_attendance')
    op.drop_index(op.f('ix_teacher_attendance_date'), table_name='teacher_attendance')
    op.drop_table('teacher_attendance')
    op.drop_index(op.f('ix_school_classes_id'), table_name='school_classes')
    op.drop_table('school_classes')
    op.drop_index(op.f('ix_push_delivery_logs_user_id'), table_name='push_delivery_logs')
    op.drop_index(op.f('ix_push_delivery_logs_status'), table_name='push_delivery_logs')
    op.drop_index(op.f('ix_push_delivery_logs_reference_id'), table_name='push_delivery_logs')
    op.drop_index(op.f('ix_push_delivery_logs_notification_type'), table_name='push_delivery_logs')
    op.drop_index(op.f('ix_push_delivery_logs_institution_id'), table_name='push_delivery_logs')
    op.drop_index(op.f('ix_push_delivery_logs_id'), table_name='push_delivery_logs')
    op.drop_table('push_delivery_logs')
    op.drop_index(op.f('ix_teachers_name'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_institution_id'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_id'), table_name='teachers')
    op.drop_table('teachers')
    op.drop_index(op.f('ix_sections_institution_id'), table_name='sections')
    op.drop_index(op.f('ix_sections_id'), table_name='sections')
    op.drop_index(op.f('ix_sections_grade_id'), table_name='sections')
    op.drop_table('sections')
    op.drop_index(op.f('ix_parents_primary_phone_normalized'), table_name='parents')
    op.drop_index(op.f('ix_parents_name'), table_name='parents')
    op.drop_index(op.f('ix_parents_institution_id'), table_name='parents')
    op.drop_index(op.f('ix_parents_id'), table_name='parents')
    op.drop_index(op.f('ix_parents_email'), table_name='parents')
    op.drop_table('parents')
    op.drop_index(op.f('ix_institution_payment_settings_institution_id'), table_name='institution_payment_settings')
    op.drop_index(op.f('ix_institution_payment_settings_id'), table_name='institution_payment_settings')
    op.drop_table('institution_payment_settings')
    op.drop_index(op.f('ix_fee_reminder_settings_institution_id'), table_name='fee_reminder_settings')
    op.drop_index(op.f('ix_fee_reminder_settings_id'), table_name='fee_reminder_settings')
    op.drop_table('fee_reminder_settings')
    op.drop_index(op.f('ix_device_tokens_user_id'), table_name='device_tokens')
    op.drop_index('ix_device_tokens_user_active', table_name='device_tokens')
    op.drop_index(op.f('ix_device_tokens_is_active'), table_name='device_tokens')
    op.drop_index(op.f('ix_device_tokens_institution_id'), table_name='device_tokens')
    op.drop_index(op.f('ix_device_tokens_id'), table_name='device_tokens')
    op.drop_index(op.f('ix_device_tokens_expo_push_token'), table_name='device_tokens')
    op.drop_table('device_tokens')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_institution_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_subjects_name'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_institution_id'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_id'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_code'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_schedule_periods_institution_id'), table_name='schedule_periods')
    op.drop_index(op.f('ix_schedule_periods_id'), table_name='schedule_periods')
    op.drop_table('schedule_periods')
    op.drop_index(op.f('ix_grades_institution_id'), table_name='grades')
    op.drop_index(op.f('ix_grades_id'), table_name='grades')
    op.drop_table('grades')
    op.drop_index(op.f('ix_events_title'), table_name='events')
    op.drop_index(op.f('ix_events_institution_id'), table_name='events')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_institutions_slug'), table_name='institutions')
    op.drop_index(op.f('ix_institutions_name'), table_name='institutions')
    op.drop_index(op.f('ix_institutions_id'), table_name='institutions')
    op.drop_index(op.f('ix_institutions_deleted_at'), table_name='institutions')
    op.drop_table('institutions')
    op.drop_table('cron_locks')
    # ### end Alembic commands ###
