"""add_fee_columns_to_school_classes

Revision ID: b5ac571fe81a
Revises: 13c11b62bf63
Create Date: 2026-04-24 18:03:07.263299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b5ac571fe81a'
down_revision: Union[str, Sequence[str], None] = '13c11b62bf63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school_classes', sa.Column('tuition_fee', sa.Float(), nullable=False, server_default='0'))
    op.add_column('school_classes', sa.Column('transport_fee', sa.Float(), nullable=False, server_default='0'))
    op.add_column('school_classes', sa.Column('other_fee', sa.Float(), nullable=False, server_default='0'))
    op.add_column('school_classes', sa.Column('total_fee', sa.Float(), nullable=False, server_default='0'))
    op.add_column('school_classes', sa.Column('fee_due_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('school_classes', 'fee_due_date')
    op.drop_column('school_classes', 'total_fee')
    op.drop_column('school_classes', 'other_fee')
    op.drop_column('school_classes', 'transport_fee')
    op.drop_column('school_classes', 'tuition_fee')
    # ### end Alembic commands ###
