"""add_index_last_notified_at

Revision ID: bf2fe42e109c
Revises: 5aedf1519642
Create Date: 2026-04-24 18:35:55.228093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf2fe42e109c'
down_revision: Union[str, Sequence[str], None] = '5aedf1519642'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_student_fees_last_notified_at'), 'student_fees', ['last_notified_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_fees_last_notified_at'), table_name='student_fees')
    # ### end Alembic commands ###
    # ### end Alembic commands ###
