"""add_index_last_called_at

Revision ID: d68199a01738
Revises: bf2fe42e109c
Create Date: 2026-04-24 18:37:27.504971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd68199a01738'
down_revision: Union[str, Sequence[str], None] = 'bf2fe42e109c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_student_fees_last_called_at'), 'student_fees', ['last_called_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_fees_last_called_at'), table_name='student_fees')
    # ### end Alembic commands ###
