"""Add storage metadata to Document model

Revision ID: d80582921a95
Revises: 4dce1a41051f
Create Date: 2026-04-05 22:13:37.604215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd80582921a95'
down_revision: Union[str, Sequence[str], None] = '4dce1a41051f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('mime_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('document_category', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('student_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_documents_student_id', 'students', ['student_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint('fk_documents_student_id', type_='foreignkey')
        batch_op.drop_column('student_id')
        batch_op.drop_column('document_category')
        batch_op.drop_column('mime_type')
        batch_op.drop_column('size')

    # ### end Alembic commands ###
