"""Sync announcements and add reads table

Revision ID: 13c11b62bf63
Revises: 544e16dad7a0
Create Date: 2026-04-24 11:53:49.808207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '13c11b62bf63'
down_revision: Union[str, Sequence[str], None] = '544e16dad7a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('is_read', sa.Integer(), nullable=True),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_institution_id'), 'notifications', ['institution_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('announcement_reads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('announcement_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('announcement_id', 'parent_id', name='uq_announcement_parent_read')
    )
    op.drop_index(op.f('ix_device_tokens_id'), table_name='device_tokens')
    op.drop_index(op.f('ix_device_tokens_token'), table_name='device_tokens')
    op.drop_index(op.f('ix_device_tokens_user_id'), table_name='device_tokens')
    op.drop_table('device_tokens')
    op.drop_index(op.f('ix_fee_reminders_fee_structure_id'), table_name='fee_reminders')
    op.drop_index(op.f('ix_fee_reminders_id'), table_name='fee_reminders')
    op.drop_index(op.f('ix_fee_reminders_institution_id'), table_name='fee_reminders')
    op.drop_index(op.f('ix_fee_reminders_student_id'), table_name='fee_reminders')
    op.drop_table('fee_reminders')
    op.add_column('announcements', sa.Column('type', sa.Enum('CLASS', 'STUDENT', name='announcementtype'), nullable=False))
    op.add_column('announcements', sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='announcementpriority'), nullable=False))
    op.add_column('announcements', sa.Column('attachment_url', sa.String(), nullable=True))
    op.add_column('announcements', sa.Column('class_id', sa.Integer(), nullable=True))
    op.add_column('announcements', sa.Column('student_id', sa.Integer(), nullable=True))
    op.add_column('announcements', sa.Column('teacher_id', sa.Integer(), nullable=False))
    op.alter_column('announcements', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('announcements', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('announcements', 'message',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('announcements', 'institution_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('announcements', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_announcements_id'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_institution_id'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_title'), table_name='announcements')
    op.create_index('ix_announcements_class_id', 'announcements', ['class_id'], unique=False)
    op.create_index('ix_announcements_created_at_desc', 'announcements', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_announcements_student_id', 'announcements', ['student_id'], unique=False)
    op.drop_constraint(op.f('announcements_created_by_id_fkey'), 'announcements', type_='foreignkey')
    op.create_foreign_key(None, 'announcements', 'teachers', ['teacher_id'], ['id'])
    op.create_foreign_key(None, 'announcements', 'grades', ['class_id'], ['id'])
    op.create_foreign_key(None, 'announcements', 'students', ['student_id'], ['id'])
    op.drop_column('announcements', 'updated_at')
    op.drop_column('announcements', 'expires_at')
    op.drop_column('announcements', 'created_by_id')
    op.drop_column('announcements', 'audience')
    op.drop_column('fee_structure', 'late_fee_per_day')
    op.drop_column('fee_structure', 'due_date')
    op.drop_column('fee_structure', 'max_late_fee')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fee_structure', sa.Column('max_late_fee', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('fee_structure', sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('fee_structure', sa.Column('late_fee_per_day', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False))
    op.add_column('announcements', sa.Column('audience', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('announcements', sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('announcements', sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('announcements', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'announcements', type_='foreignkey')
    op.drop_constraint(None, 'announcements', type_='foreignkey')
    op.drop_constraint(None, 'announcements', type_='foreignkey')
    op.create_foreign_key(op.f('announcements_created_by_id_fkey'), 'announcements', 'users', ['created_by_id'], ['id'])
    op.drop_index('ix_announcements_student_id', table_name='announcements')
    op.drop_index('ix_announcements_created_at_desc', table_name='announcements')
    op.drop_index('ix_announcements_class_id', table_name='announcements')
    op.create_index(op.f('ix_announcements_title'), 'announcements', ['title'], unique=False)
    op.create_index(op.f('ix_announcements_institution_id'), 'announcements', ['institution_id'], unique=False)
    op.create_index(op.f('ix_announcements_id'), 'announcements', ['id'], unique=False)
    op.alter_column('announcements', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('announcements', 'institution_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('announcements', 'message',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('announcements', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('announcements', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('announcements', 'teacher_id')
    op.drop_column('announcements', 'student_id')
    op.drop_column('announcements', 'class_id')
    op.drop_column('announcements', 'attachment_url')
    op.drop_column('announcements', 'priority')
    op.drop_column('announcements', 'type')
    op.create_table('fee_reminders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('institution_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('fee_structure_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fee_structure_id'], ['fee_structure.id'], name=op.f('fee_reminders_fee_structure_id_fkey')),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fee_reminders_institution_id_fkey')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fee_reminders_student_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('fee_reminders_pkey'))
    )
    op.create_index(op.f('ix_fee_reminders_student_id'), 'fee_reminders', ['student_id'], unique=False)
    op.create_index(op.f('ix_fee_reminders_institution_id'), 'fee_reminders', ['institution_id'], unique=False)
    op.create_index(op.f('ix_fee_reminders_id'), 'fee_reminders', ['id'], unique=False)
    op.create_index(op.f('ix_fee_reminders_fee_structure_id'), 'fee_reminders', ['fee_structure_id'], unique=False)
    op.create_table('device_tokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('platform', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('device_tokens_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('device_tokens_pkey'))
    )
    op.create_index(op.f('ix_device_tokens_user_id'), 'device_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_device_tokens_token'), 'device_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_device_tokens_id'), 'device_tokens', ['id'], unique=False)
    op.drop_table('announcement_reads')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_institution_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
