"""add_fee_structure_id_to_reminders

Revision ID: 544e16dad7a0
Revises: 577015823dce
Create Date: 2026-04-22 01:00:26.715281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '544e16dad7a0'
down_revision: Union[str, Sequence[str], None] = '577015823dce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fee_reminders', sa.Column('fee_structure_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_fee_reminders_fee_structure_id'), 'fee_reminders', ['fee_structure_id'], unique=False)
    op.create_foreign_key(None, 'fee_reminders', 'fee_structure', ['fee_structure_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fee_reminders', type_='foreignkey')
    op.drop_index(op.f('ix_fee_reminders_fee_structure_id'), table_name='fee_reminders')
    op.drop_column('fee_reminders', 'fee_structure_id')
    # ### end Alembic commands ###
