"""add_fee_reminders_table

Revision ID: e87ef4fd71f4
Revises: 40725f2c5fc5
Create Date: 2026-04-22 00:22:33.623046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e87ef4fd71f4'
down_revision: Union[str, Sequence[str], None] = '40725f2c5fc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fee_reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_reminders_id'), 'fee_reminders', ['id'], unique=False)
    op.create_index(op.f('ix_fee_reminders_institution_id'), 'fee_reminders', ['institution_id'], unique=False)
    op.create_index(op.f('ix_fee_reminders_student_id'), 'fee_reminders', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fee_reminders_student_id'), table_name='fee_reminders')
    op.drop_index(op.f('ix_fee_reminders_institution_id'), table_name='fee_reminders')
    op.drop_index(op.f('ix_fee_reminders_id'), table_name='fee_reminders')
    op.drop_table('fee_reminders')
    # ### end Alembic commands ###
